---
# tasks file for ansible-role-hashicorp-repo
- name: Add HashiCorp repository for AlmaLinux 9
  block:
    - name: Add HashiCorp GPG Key
      ansible.builtin.rpm_key:
        key: https://rpm.releases.hashicorp.com/gpg

    - name: Add HashiCorp repository
      ansible.builtin.yum_repository:
        name: hashicorp
        description: HashiCorp Linux repository
        baseurl: https://rpm.releases.hashicorp.com/RHEL/$releasever/$basearch/stable
        gpgcheck: yes
        gpgkey: https://rpm.releases.hashicorp.com/gpg
        state: present
      when: ansible_distribution == 'AlmaLinux' and ansible_distribution_major_version == '9'

- name: Install Packer and Vagrant on AlmaLinux 9
  block:
    - name: Install required packages
      ansible.builtin.package:
        name:
          - packer
          - vagrant
        state: present
      when: ansible_distribution == 'AlmaLinux' and ansible_distribution_major_version == '9'
